modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"

[[mods]]
modId="arthurian"
version="1.19.4-1.0.0"
displayName="Arthurian"
logoFile="arthurian.png"
credits="Lemon_Juiced"
authors="Lemon_Juiced"

description='''
Arthurian and English Mythology in Minecraft.

Made for Minecraft Monthly Modjam: https://discord.gg/khztpRSP58
Modjam #1:
· Date: 5/15/2023 - 6/15/2023
· Theme: Mythology

Requirements:
· 5 Mobs - Requirement Not Met
· 3 Weapons - Requirement Met (Ascalon, Caliburn Replica, Durandal, Excalibur)
· 2 Structures - Requirement Met (Durandal Cliff, Excalibur Shrine)
· 5 Items - Requirement Met (Hilt, Meteoric Iron Ingot, Meteoric Iron Nugget, Raw Neteoric Iron, Starsteel Ingot, Starsteel Nugget)
· Custom Models - Requirement Met (All Textures & Models Are Custom)
'''

[[dependencies.arthurian]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.arthurian]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.arthurian]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.1.3,)"
    ordering="NONE"
    side="BOTH"
